"""initial schema — creates all tables

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-13

This migration creates the entire schema (44 tables) in one step using
SQLAlchemy's metadata.create_all, rather than hand-written per-table
op.create_table() calls. This is a deliberate choice for the *first*
migration only: it lets the whole schema be applied automatically by
Render on deploy (via `alembic upgrade head` in the start command) with
no terminal access needed on your end.

Any future schema changes should use a normal autogenerated migration
(`alembic revision --autogenerate`) run by a developer with direct
database access — this file is just the one-time bootstrap.
"""
from alembic import op

# Import Base + every model so metadata is fully populated.
from app.database import Base
from app.models import *  # noqa: F401,F403

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade():
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
